<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://kit.fontawesome.com/cbb2933fde.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="../Vista/recursos/css/Stylees.css">
    <title>The Food-ders</title>
</head>
<body class="Index-Principal">
<?php include "modulos/barraSub.php" ?>
<!--Main-->
<section id="Nosotros">
    <div class="texto">
        <h2>¿Quiénes somos?</h2>
       <p>¡Bienvenido a nuestro negocio! Aquí, nos enorgullece ofrecer una amplia variedad de 
        productos de alta calidad, que incluyen embutidos y lácteos, entre otros artículos 
        esenciales para tu hogar. Nos apasiona seleccionar solo los mejores productos para 
        nuestros clientes, y estamos seguros de que encontrarás justo lo que estás buscando en 
        nuestro surtido. <br>
        Lo mejor es que pueder ser desde la comodidad de tu casa. Creemos 
        firmemente en ofrecer productos de calidad a precios razonables, y estamos seguros de 
        que te sorprenderá lo lejos que puede llegar tu dinero con nosotros.
       </p>
    </div>
    <div class="imagen1">
        <img src="../Vista/recursos/img/imagen1.jpg" alt="">
    </div>
</section>
<!--CONTENIDO-->
<section class="contenedor" id="servicio">
    <h2 class="subtitulo"> Nuestro servicio</h2>
    <div class="contenedor-servicio">
        <img src="../Vista/recursos/img/Instagram Square Pyramid Chart - CC.png" alt="">
        <div class="checklist-servicio">
            <div class="service">
                <h3 class="n-service"><span></span>Nuevas cualidades</h3>
                <p>Productos Frescos y de Calidad: Garantizar que todos los productos, incluyendo carnes y lácteos, sean frescos y de alta calidad. Esto podría incluir asociarse con proveedores locales o regionales de confianza</p>
            </div>
            <div class="service">
                <h3 class="n-service"><span></span>Lo que siempre haz querido</h3>
                <p>Ofrecer una amplia variedad de productos frescos y de alta calidad, así como opciones especializadas y alternativas, puede ayudar a atraer a una amplia base de clientes y satisfacer sus necesidades y preferencias individuales. Es importante mantenerse actualizado con las tendencias del mercado y escuchar los comentarios de los clientes para adaptar la selección de productos según la demanda.</p>
            </div>
            <div class="service">
                <h3 class="n-service"><span></span>Mejores productos</h3>
                <p>Sección de productos locales y artesanales: Destaca los productos lácteos y las carnes de productores locales y artesanos. Esto no solo apoya a la comunidad local, sino que también puede ofrecer productos únicos y de alta calidad que pueden diferenciar tu tienda de la competencia.</p>
            </div>
        </div>
    </div>
</section>
<!--MAPA-->
<section class="ubicacion" id="ubicacion">
    <h2>!VISITANOS!</h2>
<div class="maps">
    <iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d15054.602522678042!2d-99.017993!3d19.3842746!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85d1e2d45a443841%3A0x3917e2fe915ab0b7!2sVicente%20Villada%2C%2057710%20Cdad.%20Nezahualc%C3%B3yotl%2C%20M%C3%A9x.!5e0!3m2!1ses!2smx!4v1707875878348!5m2!1ses!2smx" width="800" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>
</div>
</section>
<!--PIE DE PAGINA-->
<footer class="pie" id="contacto">
<?php include "modulos/PiePagina.php" ?>
   </footer>
</body>
</html>